version = 0.1

[default.deploy.parameters]
stack_name = "Url-Shortener-App-Souvik"
resolve_s3 = true
s3_prefix = "Url-Shortener-App-Souvik"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
