name: Branch-Based Regional Deployment

on:
  push:
    branches:
      - development
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  RESOURCE_NAME_PREFIX: 'Souvik'

  DEVELOPMENT_AWS_REGION: ${{ vars.DEVELOPMENT_AWS_REGION }}

  PRODUCTION_AWS_REGION: ${{ vars.PRODUCTION_AWS_REGION }}

jobs:
  development:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'development' && github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DEVELOPMENT_AWS_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Building SAM Project
        run: sam build

      - name: Deploying the Application
        run: |
          sam deploy \
            --stack-name "Url-Shortener-App-${RESOURCE_NAME_PREFIX}-dev" \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides JwtSecret=${{ env.JWT_SECRET }} \
              EnvName=${GITHUB_REF##*/} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

  production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main' && github.ref_type == 'branch'
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.PRODUCTION_AWS_REGION }}

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Building SAM Project
        run: sam build

      - name: Deploying the Application
        run: |
          sam deploy \            
            --stack-name "Url-Shortener-App-${RESOURCE_NAME_PREFIX}-prod" \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides JwtSecret=${{ env.JWT_SECRET }} \
              EnvName=${GITHUB_REF##*/} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
